name: master deploy

on:   
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: yarn install, build, and test
        # working-directory: ./frontend
        run: |
          yarn install
          yarn build

      - name: master deploy
        run: |
          git config --global user.name 'jik0090'
          git config --global user.email 'jik0090@naver.com'
          git add .
          git commit -m "Automated report"
          git push