name: master deploy

on:   
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Use Node.js 
        uses: actions/setup-node@v1

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
      

      - name: Save building file
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - name: Save source file
      - uses: actions/upload-artifact@v1
        with:
          name: src
          path: src

      - name: master deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: dist