name: master deploy

on:   
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
          git config --local user.email "jik0090@naver.com"
          git config --local user.name "jik0090"
          yarn deploy


      # - name: master deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BRANCH: master
      #     FOLDER: .